Reverto to earlier frontend code job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -332,65 +332,6 @@ jobs:
             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
 
-  # smoke-test:
-  #   docker:
-  #     - image: python:3.7-alpine3.11
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           apk add --update npm
-  #           apk add --update nodejs
-  #           apk add curl
-  #           pip3 install awscli
-              
-  #     - attach_workspace:
-  #         at: ~/
-
-  #     - run:
-  #         name: Confirm workspace attachment worked.
-  #         command: |
-  #           # Fetch and prepare the BACKEND_IP env var
-  #           cd .circleci/ansible
-  #           cat inventory.txt
-
-
-  #     - run:
-  #         name: Backend smoke test.
-  #         command: |
-  #           # Fetch and prepare the BACKEND_IP env var
-  #           cd .circleci/ansible
-  #           export BACKEND_IP=$(cat inventory.txt | awk 'END{print}')
-  #           export API_URL="http://${BACKEND_IP}:3030"
-  #           echo "API_URL = ${API_URL}"
-  #           if curl "${API_URL}/api/status" | grep "ok"
-  #           #if curl -s http://google.com
-  #           then
-  #               return 0
-  #           else
-  #               return 1
-  #           fi
-  #     - run:
-  #         name: Frontend smoke test.
-  #         command: |
-  #           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-2.amazonaws.com/#/employees"            
-  #           echo ${URL} 
-  #           if curl -s ${URL} | grep "Welcome"
-  #           then
-  #               # Change this to 0 after the job fails
-  #             return 0
-  #           else
-  #             return 1
-  #           fi
-      
-  #     - slack/notify:
-  #         channel: D03NGPP0EN8 #channel
-  #         event: fail
-
-      # - destroy-environment:
-      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-
   smoke-test:
     docker:
       - image: python:3.7-alpine3.11
@@ -406,21 +347,80 @@ jobs:
               
       - attach_workspace:
           at: ~/
+
+      - run:
+          name: Confirm workspace attachment worked.
+          command: |
+            # Fetch and prepare the BACKEND_IP env var
+            cd .circleci/ansible
+            cat inventory.txt
+
+
       - run:
           name: Backend smoke test.
           command: |
-            export BACKEND_IP=$(aws ec2 describe-instances \
-            --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --output text) 
+            # Fetch and prepare the BACKEND_IP env var
+            cd .circleci/ansible
+            export BACKEND_IP=$(cat inventory.txt | awk 'END{print}')
             export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"      
-            if curl "${API_URL}/api/status" | grep "ok"; then exit 0; else exit 1; fi
+            echo "API_URL = ${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            #if curl -s http://google.com
+            then
+                return 0
+            else
+                return 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-2.amazonaws.com/#/employees"            
             echo ${URL} 
-            if curl ${URL} | grep "Welcome"; then exit 0; else exit 1; fi
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              return 0
+            else
+              return 1
+            fi
+      
+      - slack/notify:
+          channel: D03NGPP0EN8 #channel
+          event: fail
+
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+
+  # smoke-test:
+  #   docker:
+  #     - image: python:3.7-alpine3.11
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           apk add --update npm
+  #           apk add --update nodejs
+  #           apk add curl
+  #           pip3 install awscli
+              
+  #     - attach_workspace:
+  #         at: ~/
+  #     - run:
+  #         name: Backend smoke test.
+  #         command: |
+  #           export BACKEND_IP=$(aws ec2 describe-instances \
+  #           --query 'Reservations[*].Instances[*].PublicIpAddress' \
+  #           --output text) 
+  #           export API_URL="http://${BACKEND_IP}:3030"
+  #           echo "${API_URL}"      
+  #           if curl "${API_URL}/api/status" | grep "ok"; then exit 0; else exit 1; fi
+  #     - run:
+  #         name: Frontend smoke test.
+  #         command: |
+  #           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-2.amazonaws.com/#/employees"            
+            # echo ${URL} 
+            # if curl ${URL} | grep "Welcome"; then exit 0; else exit 1; fi
       # - destroy-environment:
       #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
